# Uncomment this line to define a global platform for your project
platform :osx, '10.12'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DroidID' do
pod 'FirebaseOSX', '>= 2.5.0'
pod 'Locksmith’, ‘>= 2.0.8’
end

