# Uncomment this line to define a global platform for your project
platform :osx, '10.12'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DroidID' do
pod 'FirebaseOSX', '>= 2.5.1'
pod 'Locksmith’, ‘>= 3.0.0’
end

